name: "Validate Gradle Wrapper"
on:
  pull_request:
    paths:
      - '.github/workflows/validate_gradle_wrapper.yml'
      - 'gradle/**'
      - 'gradlew'
      - 'gradlew.bat'

jobs:
  validation:
    name: "Wrapper validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - uses: gradle/wrapper-validation-action@2a9956c214b2b4b63544570479c926e7a121218e
